openapi: 3.0.0
info:
  title: StudentLounge
  version: 1.0.0
  description: Documentation to alter a project
paths:
  /projects/{projectId}:
    patch:
      tags:
        - projects
      summary: Alter a project
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: integer
          description: ID of the project
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token for authentication
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the project
                  example: "Project Alpha Updated"
                description:
                  type: string
                  description: Description of the project
                  example: "An updated description of the project about AI advancements."
                url:
                  type: string
                  description: URL of the project
                  example: "http://example.com/project-alpha-updated"
      responses:
        '200':
          description: Project altered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Project altered successfully"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You need to be logged in to alter a project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You are not allowed to alter this project"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "The project does not exist"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Something went wrong. Please try again later"
