openapi: 3.0.0
info:
  title: studentLounge
  version: 1.0.0
  description: Documentation for the endpoint to get all favorites of a post
paths:
  /posts/{postId}/favorite:
    get:
      summary: Get all favorites of a post
      tags:
        - posts
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
          description: ID of the post to get favorites from
      responses:
        '200':
          description: OK - Favorites retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  post:
                    type: object
                    properties:
                      postId:
                        type: integer
                        description: ID of the post
                      title:
                        type: string
                        description: Title of the post
                      favorites:
                        type: array
                        items:
                          type: object
                          properties:
                            userId:
                              type: integer
                              description: ID of the user who favorited the post
                            name:
                              type: string
                              description: Name of the user who favorited the post
        '404':
          description: Not found - The post does not exist
          content:
            application/json:
              example:
                message: "Post not found"
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                message: "Something went wrong. Please try again later"
components:
  schemas:
    Alumni:
      type: object
      properties:
        alumniId:
          type: integer
          description: ID of the alumni
        name:
          type: string
          description: Name of the alumni
