openapi: 3.0.0
info:
  title: StudentLounge
  version: 1.0.0
  description: documentation for alumni account deletion
paths:
  /alumni/deleteAccount:
    delete:
      tags:
        - alumni
      summary: Delete Alumni Account
      description: Delete the account of the authenticated alumni
      security:
        - bearerAuth: []
      responses:
        200:
          description: Account deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Account deleted successfully
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: You need to be authenticated to delete an account
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The account you are trying to delete does not exist
        500:
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Something went wrong. Please try again later
