openapi: 3.0.0
info:
  title: StudentLounge
  version: 1.0.0
  description: documentation for alumni account information retrieval
paths:
  /alumni/{alumniId}:
    get:
      tags:
        - alumni
      summary: Get information of a specific alumni
      description: Get information of a specific alumni
      parameters:
        - in: path
          name: alumniId
          required: true
          schema:
            type: integer
          description: The ID of the alumni
        - in: header
          name: token
          required: true
          schema:
            type: string
          description: JWT token
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: john@example.com
                  name:
                    type: string
                    example: John Doe
                  currentCompany:
                    type: string
                    example: SONAE
                  skills:
                    type: array
                    items:
                      type: string
                    example: ["JavaScript", "React", "Node.js", "SQL"]
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: You need to be logged in to get information about an alumni
        404:
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The alumni does not exist
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Something went wrong. Please try again later
