openapi: 3.0.0
info:
  title: StudentLounge
  version: 1.0.0
  description: documentation for alumni account deletion
paths:
  /alumni/{alumniId}:
    delete:
      tags:
        - alumni
      summary: Delete an alumni account
      description: Delete the authenticated user's own alumni account with `/me` or any alumni account by specifying the alumni ID (admin only).
      parameters:
        - in: path
          name: alumniId
          required: true
          description: The ID of the alumni to delete or 'me' to delete own account
          schema:
            type: string
            example: '5'
      responses:
        200:
          description: Account deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Account deleted successfully
        401:
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized access
        403:
          description: Forbidden access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Forbidden: You do not have permission to delete this account
        404:
          description: Alumni account not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Alumni account not found
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
