openapi: 3.0.0
info:
  title: StudentLounge
  version: 1.0.0
  description: Documentation to get all events
paths:
  /events:
    get:
      tags:
        - events
      summary: Get all the events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    eventId:
                      type: integer
                      example: 123
                    title:
                      type: string
                      example: "Tech Conference 2024"
                    date:
                      type: string
                      example: "2024-07-15"
                    location:
                      type: string
                      example: "b204"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "There are no events"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Something went wrong. Please try again later"
