openapi: 3.0.0
info:
  title: StudentLounge
  version: 1.0.0
  description: Documentation to create a new event
paths:
  /events:
    post:
      tags:
        - events
      summary: Create a new event
      parameters:
        - in: header
          name: token
          required: true
          schema:
            type: string
          description: Authentication token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Tech Conference 2024"
                date:
                  type: string
                  example: "06/08/24"
                location:
                  type: string
                  example: "Auditório"
              required:
                - title
                - date
                - location
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "The event was created successfully"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You need to be logged in to create a new event"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Your account lacks the necessary permissions for this action"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Something went wrong. Please try again later"
